import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Link, useLocation } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { ThemeToggle } from "@/components/ThemeToggle";
import { 
  BookOpen, Zap, Target, Users, Search, ArrowRight, CheckCircle, 
  Star, Flame, Award, TrendingUp, Clock, Lightbulb
} from "lucide-react";

const GRADE_CATEGORIES = [
  { id: "primary", label: "Primary", grades: ["P1", "P2", "P3", "P4", "P5", "P6", "P7", "P8"], color: "from-blue-500 to-blue-600" },
  { id: "secondary", label: "Secondary", grades: ["F1", "F2", "F3", "F4"], color: "from-purple-500 to-purple-600" },
  { id: "igcse", label: "IGCSE", grades: ["IGCSE"], color: "from-green-500 to-green-600" },
];

const SUBJECTS = [
  { name: "Mathematics", icon: "📐", color: "bg-blue-100 dark:bg-blue-900" },
  { name: "English", icon: "📚", color: "bg-purple-100 dark:bg-purple-900" },
  { name: "Science", icon: "🧪", color: "bg-green-100 dark:bg-green-900" },
  { name: "Biology", icon: "🦠", color: "bg-teal-100 dark:bg-teal-900" },
  { name: "Chemistry", icon: "⚗️", color: "bg-orange-100 dark:bg-orange-900" },
  { name: "Physics", icon: "⚡", color: "bg-yellow-100 dark:bg-yellow-900" },
  { name: "History", icon: "📜", color: "bg-red-100 dark:bg-red-900" },
  { name: "Geography", icon: "🗺️", color: "bg-indigo-100 dark:bg-indigo-900" },
];

const FEATURES = [
  {
    icon: BookOpen,
    title: "AI-Generated Study Notes",
    description: "Expert-written notes for every topic, generated by AI and reviewed by teachers"
  },
  {
    icon: Target,
    title: "Smart Practice Questions",
    description: "Questions organized by difficulty, with detailed explanations for every answer"
  },
  {
    icon: Zap,
    title: "100+ Past Papers",
    description: "KCSE, KCPE, and IGCSE papers with solutions and video explanations"
  },
  {
    icon: Flame,
    title: "Build Your Streak",
    description: "Study daily and build an unbreakable learning streak"
  },
];

const TESTIMONIALS = [
  {
    name: "Sarah K.",
    school: "Nairobi High School",
    text: "Tkrell helped me improve my Math grade from C+ to A-. The notes are so clear!",
    grade: "A-"
  },
  {
    name: "James M.",
    school: "Mombasa Secondary",
    text: "I love the daily challenges. They keep me motivated to study every day.",
    grade: "A"
  },
  {
    name: "Mary N.",
    school: "Kisumu Girls",
    text: "The past papers section is amazing. I practiced 50 papers before my final exam.",
    grade: "A"
  },
];

const STATS = [
  { number: "50,000+", label: "Students Learning" },
  { number: "10,000+", label: "Study Notes" },
  { number: "500+", label: "Past Papers" },
  { number: "95%", label: "Pass Rate" },
];

export default function Home() {
  const { isAuthenticated, user } = useAuth();
  const [, setLocation] = useLocation();
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedGrade, setSelectedGrade] = useState<string | null>(null);

  const handleStartStudying = () => {
    if (isAuthenticated) {
      setLocation("/dashboard");
    } else {
      setLocation("/profile");
    }
  };

  const handleGradeSelect = (grade: string) => {
    if (isAuthenticated) {
      setLocation(`/dashboard?grade=${grade}`);
    } else {
      setLocation("/profile");
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-background via-background to-primary/5">
      {/* Navigation Bar */}
      <nav className="border-b bg-card/50 backdrop-blur-sm sticky top-0 z-50">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <Link href="/">
            <div className="flex items-center gap-2 cursor-pointer hover:opacity-80 transition">
              <BookOpen className="h-8 w-8 text-primary" />
              <span className="text-2xl font-bold bg-gradient-to-r from-primary to-purple-600 bg-clip-text text-transparent">Tkrell</span>
            </div>
          </Link>
          
          <div className="hidden md:flex items-center gap-4 flex-1 mx-8">
            <div className="relative flex-1 max-w-md">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder="Search subjects, topics..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-10"
              />
            </div>
          </div>

          <div className="flex items-center gap-2">
            <ThemeToggle />
            {isAuthenticated ? (
              <>
                <span className="text-sm font-medium hidden sm:inline">{user?.name}</span>
                <Link href="/dashboard">
                  <Button className="gap-2">
                    <Flame className="h-4 w-4" />
                    Dashboard
                  </Button>
                </Link>
              </>
            ) : (
              <>
                <Link href="/profile">
                  <Button variant="outline">Sign In</Button>
                </Link>
                <Link href="/profile">
                  <Button className="gap-2">
                    Get Started
                    <ArrowRight className="h-4 w-4" />
                  </Button>
                </Link>
              </>
            )}
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="container mx-auto px-4 py-20 text-center">
        <div className="max-w-3xl mx-auto space-y-6">
          <div className="inline-block px-4 py-2 bg-primary/10 rounded-full border border-primary/20">
            <span className="text-sm font-semibold text-primary">🎓 Trusted by 50,000+ Students in Kenya</span>
          </div>
          
          <h1 className="text-5xl md:text-6xl font-bold leading-tight">
            Master Every Subject with <span className="bg-gradient-to-r from-primary to-purple-600 bg-clip-text text-transparent">AI-Powered Learning</span>
          </h1>
          
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Get expert study notes, practice questions, and past papers for KCPE, KCSE, and IGCSE. Build your learning streak and compete with students from your school.
          </p>

          <div className="flex gap-4 justify-center pt-4">
            <Button size="lg" className="gap-2" onClick={handleStartStudying}>
              Start Studying Free
              <ArrowRight className="h-5 w-5" />
            </Button>
            <Button size="lg" variant="outline">
              Watch Demo
            </Button>
          </div>

          {/* Stats */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 pt-12">
            {STATS.map((stat, i) => (
              <div key={i} className="p-4 bg-card rounded-lg border">
                <div className="text-2xl font-bold text-primary">{stat.number}</div>
                <div className="text-sm text-muted-foreground">{stat.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="container mx-auto px-4 py-20">
        <h2 className="text-4xl font-bold text-center mb-12">Why Choose Tkrell?</h2>
        <div className="grid md:grid-cols-2 gap-6">
          {FEATURES.map((feature, i) => (
            <Card key={i} className="hover:shadow-lg transition">
              <CardHeader>
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-primary/10 rounded-lg">
                    <feature.icon className="h-6 w-6 text-primary" />
                  </div>
                  <CardTitle>{feature.title}</CardTitle>
                </div>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground">{feature.description}</p>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      {/* Gamification Preview */}
      <section className="container mx-auto px-4 py-20 bg-card rounded-2xl border">
        <h2 className="text-4xl font-bold text-center mb-12">Level Up Your Learning</h2>
        <div className="grid md:grid-cols-3 gap-8">
          <div className="text-center">
            <div className="inline-block p-4 bg-primary/10 rounded-full mb-4">
              <Flame className="h-8 w-8 text-orange-500" />
            </div>
            <h3 className="text-xl font-bold mb-2">Build Streaks</h3>
            <p className="text-muted-foreground">Study daily and build an unbreakable streak. Don't break the chain!</p>
          </div>
          <div className="text-center">
            <div className="inline-block p-4 bg-primary/10 rounded-full mb-4">
              <Award className="h-8 w-8 text-yellow-500" />
            </div>
            <h3 className="text-xl font-bold mb-2">Earn Badges</h3>
            <p className="text-muted-foreground">Unlock achievements as you progress. Show off your accomplishments!</p>
          </div>
          <div className="text-center">
            <div className="inline-block p-4 bg-primary/10 rounded-full mb-4">
              <TrendingUp className="h-8 w-8 text-green-500" />
            </div>
            <h3 className="text-xl font-bold mb-2">Track Progress</h3>
            <p className="text-muted-foreground">See your improvement over time with detailed analytics and insights.</p>
          </div>
        </div>
      </section>

      {/* Grade Selection */}
      <section className="container mx-auto px-4 py-20">
        <h2 className="text-4xl font-bold text-center mb-12">Choose Your Level</h2>
        <div className="grid md:grid-cols-3 gap-6">
          {GRADE_CATEGORIES.map((category) => (
            <Card key={category.id} className="hover:shadow-lg transition cursor-pointer">
              <CardHeader>
                <CardTitle className={`bg-gradient-to-r ${category.color} bg-clip-text text-transparent`}>
                  {category.label}
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-2 gap-2">
                  {category.grades.map((grade) => (
                    <Button
                      key={grade}
                      variant="outline"
                      size="sm"
                      onClick={() => handleGradeSelect(grade)}
                      className="hover:bg-primary hover:text-primary-foreground"
                    >
                      {grade}
                    </Button>
                  ))}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      {/* Testimonials */}
      <section className="container mx-auto px-4 py-20">
        <h2 className="text-4xl font-bold text-center mb-12">What Students Say</h2>
        <div className="grid md:grid-cols-3 gap-6">
          {TESTIMONIALS.map((testimonial, i) => (
            <Card key={i}>
              <CardHeader>
                <div className="flex items-center justify-between mb-2">
                  <div>
                    <CardTitle className="text-lg">{testimonial.name}</CardTitle>
                    <CardDescription>{testimonial.school}</CardDescription>
                  </div>
                  <div className="text-2xl font-bold text-green-600">{testimonial.grade}</div>
                </div>
                <div className="flex gap-1">
                  {[...Array(5)].map((_, i) => (
                    <Star key={i} className="h-4 w-4 fill-yellow-400 text-yellow-400" />
                  ))}
                </div>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground italic">"{testimonial.text}"</p>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      {/* CTA Section */}
      <section className="container mx-auto px-4 py-20 text-center bg-gradient-to-r from-primary/10 to-purple-600/10 rounded-2xl border">
        <h2 className="text-4xl font-bold mb-4">Ready to Ace Your Exams?</h2>
        <p className="text-xl text-muted-foreground mb-8 max-w-2xl mx-auto">
          Join thousands of students who are already improving their grades with Tkrell.
        </p>
        <Button size="lg" className="gap-2" onClick={handleStartStudying}>
          Start Your Free Trial
          <ArrowRight className="h-5 w-5" />
        </Button>
      </section>

      {/* Footer */}
      <footer className="border-t mt-20 py-12 bg-card/50">
        <div className="container mx-auto px-4">
          <div className="grid md:grid-cols-4 gap-8 mb-8">
            <div>
              <h3 className="font-bold mb-4">Tkrell</h3>
              <p className="text-sm text-muted-foreground">AI-powered learning platform for Kenyan students.</p>
            </div>
            <div>
              <h4 className="font-semibold mb-4">Product</h4>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li><Link href="/">Features</Link></li>
                <li><Link href="/">Pricing</Link></li>
                <li><Link href="/">FAQ</Link></li>
              </ul>
            </div>
            <div>
              <h4 className="font-semibold mb-4">Company</h4>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li><Link href="/">About</Link></li>
                <li><Link href="/">Blog</Link></li>
                <li><Link href="/">Contact</Link></li>
              </ul>
            </div>
            <div>
              <h4 className="font-semibold mb-4">Legal</h4>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li><Link href="/">Privacy</Link></li>
                <li><Link href="/">Terms</Link></li>
                <li><Link href="/">Cookies</Link></li>
              </ul>
            </div>
          </div>
          <div className="border-t pt-8 text-center text-sm text-muted-foreground">
            <p>&copy; 2025 Tkrell. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
